<?
/** @var Application $this */
/** @var array $context */
?>

<? $anotherLang = $this->getCurrentLanguage() == 'ru' ? 'en' : 'ru'?>
<h1><?= $this->translate('vstu_header') ?> <small><a href="/change-lang.php?lang=<?= $anotherLang ?>"><?= strtoupper($anotherLang) ?></a></small></h1>

<? $total = 0 ?>
<? foreach ($context['publications'] as $year => $list): ?>
    <h3><?= $year ?></h3>
    <ol>
        <? foreach ($list as $item): ?>
            <li><?= isset($item[$this->getCurrentLanguage()]) ? $item[$this->getCurrentLanguage()] : '-' ?></li>
            <? $total++ ?>
        <? endforeach ?>
    </ol>
<? endforeach ?>

<h3><?= $this->translate('Total') ?>: <big><?= $total ?></big></h3>